# Generated by Django 3.2.5 on 2021-07-19 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=8)),
                ('public', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public', to='publics.public')),
            ],
            options={
                'db_table': 'admins',
            },
        ),
    ]
