# Generated by Django 3.2.5 on 2021-07-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20210719_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='public',
        ),
    ]
