# Generated by Django 3.2.5 on 2021-07-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0005_remove_public_admin'),
        ('admins', '0004_remove_admin_public'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
