# Generated by Django 3.2.5 on 2021-07-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=8)),
                ('cost', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'publics',
            },
        ),
    ]
