# Generated by Django 3.2.5 on 2021-07-19 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_remove_admin_public'),
        ('publics', '0002_auto_20210719_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='public',
            old_name='cost',
            new_name='paymeny',
        ),
        migrations.AddField(
            model_name='public',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admins.admin'),
            preserve_default=False,
        ),
    ]
