# Generated by Django 3.2.5 on 2021-07-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0003_auto_20210719_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='public',
            old_name='paymeny',
            new_name='cost',
        ),
    ]
